export const employeesList = [{
    name: 'Daniel Alves da Silva',
    active: true,
    cpf: '000.000.000-99',
    role: 'Cargo 1',
    job: 'Ativ 00',
},
{
    name: 'Giselle Torres Lopes',
    active: true,
    cpf: '000.000.000-81',
    role: 'Ativ 00',
    job: 'Cargo2',
},
{
    name: 'José',
    active: false,
    cpf: '128.456.789-10',
    role: 'Desenvolvedor',
    job: 'Desenvolvimento',
},
{
    name: 'João',
    active: false,
    cpf: '126.456.789-11',
    role: 'Desenvolvedor',
    job: 'Desenvolvimento',
},
{
    name: 'Giselle Torres Lopes',
    active: false,
    cpf: '000.000.000-28',
    role: 'Ativ 00',
    job: 'Cargo2',
},
{
    name: 'José',
    active: false,
    cpf: '128.456.789-20',
    role: 'Desenvolvedor',
    job: 'Desenvolvimento',
},
{
    name: 'João',
    active: false,
    cpf: '126.456.789-30',
    role: 'Desenvolvedor',
    job: 'Desenvolvimento',
},
{
    name: 'Giselle Torres Lopes',
    active: false,
    cpf: '000.000.000-48',
    role: 'Ativ 00',
    job: 'Cargo2',
},
{
    name: 'José',
    active: false,
    cpf: '128.456.789-40',
    role: 'Desenvolvedor',
    job: 'Desenvolvimento',
},
{
    name: 'João',
    active: false,
    cpf: '126.456.789-50',
    role: 'Desenvolvedor',
    job: 'Desenvolvimento',
},
{
    name: 'Giselle Torres Lopes',
    active:false ,
    cpf: '000.000.000-68',
    role: 'Ativ 00',
    job: 'Cargo2',
},
{
    name: 'José',
    active: false,
    cpf: '128.456.789-70',
    role: 'Desenvolvedor',
    job: 'Desenvolvimento',
},
{
    name: 'João',
    active: false,
    cpf: '126.456.789-80',
    role: 'Desenvolvedor',
    job: 'Desenvolvimento',
},
{
    name: 'Giselle Torres Lopes',
    active: false,
    cpf: '000.000.000-98',
    role: 'Ativ 00',
    job: 'Cargo2',
},
{
    name: 'José',
    active: false,
    cpf: '128.456.789-11',
    role: 'Desenvolvedor',
    job: 'Desenvolvimento',
},
{
    name: 'João',
    active: false,
    cpf: '126.456.789-12',
    role: 'Desenvolvedor',
    job: 'Desenvolvimento',
},
{
    name: 'Giselle Torres Lopes',
    active: false,
    cpf: '000.000.000-82',
    role: 'Ativ 00',
    job: 'Cargo2',
},
{
    name: 'José',
    active: false,
    cpf: '128.456.789-13',
    role: 'Desenvolvedor',
    job: 'Desenvolvimento',
},
{
    name: 'João',
    active: false,
    cpf: '126.456.789-14',
    role: 'Desenvolvedor',
    job: 'Desenvolvimento',
},
{
    name: 'Giselle Torres Lopes',
    active:false ,
    cpf: '000.000.000-85',
    role: 'Ativ 00',
    job: 'Cargo2',
},
{
    name: 'José',
    active: false,
    cpf: '128.456.789-16',
    role: 'Desenvolvedor',
    job: 'Desenvolvimento',
},
{
    name: 'João',
    active: false,
    cpf: '126.456.789-17',
    role: 'Desenvolvedor',
    job: 'Desenvolvimento',
},
{
    name: 'Giselle Torres Lopes',
    active:false ,
    cpf: '000.000.001-88',
    role: 'Ativ 00',
    job: 'Cargo2',
},
{
    name: 'José',
    active: false,
    cpf: '128.456.781-10',
    role: 'Desenvolvedor',
    job: 'Desenvolvimento',
},
{
    name: 'João',
    active: false,
    cpf: '126.456.782-10',
    role: 'Desenvolvedor',
    job: 'Desenvolvimento',
}

]

